# Introduction

Colorectal cancer (CRC) is the third most commonly diagnosed cancer in the US [@siegel2021]. Despite an overall decline in over the last two decades, it is known that individuals younger than 50 years [@weinberg2019] have shown an increasing trend in incidence, which is likely to hold in the near future. The majority of patients (about 75%, regardless of age) present at diagnosis what is known as "locally advanced disease". Locally advanced disease is a term used to group malignancies that range from those tumors that have only invaded the colonic mucosa to those that have spread to adjacent lymph nodes(stages IIA-IIIC) [@siegel2020]. 

In biomedical research, there is an active area of interest in novel treatment strategies that can be used to treat locally advanced disease in CRC. In this regard, an increasing body of evidence has shown that neoadjuvant chemotherapy (defined as chemotherapy administered to treat tumors before surgical resection) is able to reduce tumor size, facilitate resection, and improve completion rates in CRC [@benson2020;@roth2020;@zhou2013;@sauer2012]. The standard of care in neoadjuvant chemotherapy (NAC) consists in the use of maximum-tolerated doses (MTDs) of a cytotoxic drug. For CRC, the fluoropyrimidine 5-fluorouracil (5-FU) is the most commonly used cytotoxic agent used either alone or in combination with other drugs that aid its therapeutic effects [@grothey2018]. 

Although the goal of MTD NAC is to reduce tumor burden as much as possible, its associated toxicity makes necessary the delivery of therapy in a cyclic manner. For example, the FOLFOX regimen (a combination of leucovorin, 5-FU and oxaliplatin) is delivered in cycles that last two weeks; only the first 48 hours are of active infusion, followed by 12 days of rest [@garciaaguilar2015;@allegra2011]. Because a complete MTD NAC treatment may last between 3-4 cycles (6-8 weeks)[@karoui2015], the rest periods between each cycle present an opportunity for the tumor to recover and develop resistance. Indeed, it has been shown that MTD NAC is associated with re-growth of tumor cells and the development of drug resistance [@scharovsky2009;@boyer2006]. Altogether, the shortcomings of MTD NAC have demonstrated the need of new therapy strategies that can effectively reduce tumor burden while minimizing the associated undesirable side-effects caused by high-dose chemotherapy.

During the last decade, the biological effect of chemotherapeutic drugs at doses below the MTD threshold started to be explored. The term “metronomic chemotherapy” was coined to describe chemotherapy that involves the use of lower but active doses of chemotherapeutic drugs without prolonged rest periods in between [@kerbel2004]. Early studies on metronomic chemotherapy (MET), showed that the targets of this type of treatment were the endothelial cells of the tumor, which could not recover due to the continuous delivery of the drugs [@kerbel2004;@genfors2016], which translated in an anti-angiogenic effect [@browder2000].

Various studies have explored the use of MET in recurring and late-stage malignancies such as colon, glioma, breast, and ovarian cancer where it has been shown to improve survival [@huang2017;@reardon2009], reduce toxicity [@masuda2014], and cause high pathological complete response (no residual invasive disease on pathological evaluation) [@hildebrand2016]. However, the potential use of MET as an effective alternative to MTD NAC in CRC has not been examined so far.

More specifically, although it is assumed that the main effect of MET is its ability to disrupt the angiogenic program of tumors by impairing blood vessel development, it is not known how this effect varies between different types of malignancies. In particular, it is possible that the anti-angiogenic effect of MET is heavily dependent of the anatomic location of the tumor, as it is known from preclinical studies that the tumor milieu plays a critical role in the response to treatment [@li2017;@devaud2014]. For example, in the case of malignancies that arise in a lipid-rich environment (such as the colon), it has been shown that a hypoxia-driven shift in lipid metabolism can be coupled with tumor growth without the presence of a dense vascular network [@iwamoto2018]. Therefore, there is a need for an improved understanding of the metabolic implications of MET NAC in CRC in regard to angiogenesis, and how these changes contrast with those elicited by MTD NAC.

In this study, we hypothesized that the differences in dosing and frequency of administration between MTD and MET NAC would cause distinct changes in the angiogenic program of primary colorectal tumors that could be analyzed to better understand the opportunities and pitfalls of MET NAC when used on CRC. To this end, we used a dual approach to examine 'high level' and 'low level' changes in angiogenesis. Firstly, we used endoscopic diffuse reflectance spectroscopy (DRS), an optical technique that enables quantification of physiological metrics of perfusion in tissue such as oxygen saturation ($\mbox{StO}_{2}$), oxyhemoglobin ($\mbox{HbO}_{2}$), and deoxyhemoglobin (HbO), to study the 'high level' effect of therapy in tumor perfusion. Because DRS is non-destructive, and relatively low-cost, it is useful to obtain an overall assessment of tumor perfusion and response to therapy [@cochran2018;@ueda2012].

Secondly, we also examined the genes (via mRNA expression) involved in the classical hypoxia-inducible factor 1 (HIF-1A) and vascular endothelial growth factor (VEGF) angiogenic axis to examine molecular ('low level') changes that could provide the rationale for the observed changes in perfusion obtained via DRS. In additionh, gene expression data were used to gain insight in the metabolic alterations that therapy progression causes in the tumor for both MET and MTD NAC. Our study addresses the need to connect 'high level' reporters of perfusion of DRS with molecular changes via qPCR to better understand the challenges and opportunities of MTD and MET NAC strategies in CRC.
