# Materials and Methods
 
## Animal model

All procedures were approved by the University of Arkansas Institutional Animal Care and Use Committee under protocol 21024. An azoxymethane (AOM) model of CRC was used where nine-week-old female A/J mice (000646,The Jackson Laboratory) received AOM injections (A5486, Millipore Sigma) at a dose of 10 mg/kg once a week for six weeks [@neufert2007]. After acclimation for one week upon arrival mice received AOM injections (Figure \@ref(fig:study-design),A); mice were weighed daily and received a combination or rodent chow (8640, Teklad) and hydrogel (Nutra-Gel, AIN-93, Bio-Serv); if weight loss was greater than 10% (compared to the weight on the first day of AOM injections), they received 1500 $\mu$L of 0.9% sterile saline solution (S5825, Teknova) via subcutaneous injection.
 
## Endoscopic Imaging

At 16 weeks after the last AOM injection the size of tumors was periodically assessed using a veterinary colonoscopy system (ColoVIEW, Karl Storz) as we have previously described [@mundo2020]. Briefly, mice were anesthetized using 2% isoflurane using a precision vaporizer and placed on a heating pad set at $42^{\circ}$C to maintain body temperature through the procedure. Endoscopic procedures began when mice had no pedal reflex.  Fecal matter was removed by flushing the colon with 0.9% sterile saline, and the endoscopic examination consisted in the careful insertion of the endoscopic sheath containing the telescope up to a flexure at approximately 4 cm as it has been reported elsewhere [@becker2005]. From there, the examination sheath was slowly retracted from the colon while acquiring imaging data (pictures, video) to determine tumor location; tumors were labelled sequentially following the proximal to distal orientation and their size was graded relative to the circumference of the colon [@becker2006]. Once tumors were determined to be ~ 1mm in diameter mice were randomly distributed in different chemotherapy groups.

## Chemotherapy

Chemotherapy was based on 5-FU (F6627, Millipore Sigma), which was first solubilized in dimethyl sulfoxide (97063-136, VWR) to a concentration of 50 mg/mL. This solution was then diluted in sterile saline to concentrations of 3.0 mg/mL (for the MTD group) and of 1.2 mg/mL (for the MET group), stored at -20$^\circ$C and thawed before administration. Mice were randomly distributed between maximum-tolerated (MTD, n=27), metronomic (MET, n=20) and control (CG, n=14) groups. All therapy was provided via intraperitoneal injection as follows: MTD, 20 mg/kg of 5-FU for five consecutive days every other week; MET, 8 mg/kg of 5-FU every other day three times a week; CG, 200 $\mu$L of sterile saline every other day (Figure \@ref(fig:study-design)A). Dosing and schedule for administration were determined using both reported MTD of 5-FU MTD in mice [@azrak2004], and the NAC cycling in the clinical setting. For MET, we followed previously reported MET 5-FU dosing in mice [@fioravanti2009;@orecchioni2018]. The next day of the first treatment injection (either 5-FU or saline), mice started to receive endoscopic examination for the acquisition of DRS and biopsies.

```{r,study-design,fig.align='center',fig.width=8,echo=FALSE, fig.cap='(ref:study-design-caption)'}
grid.raster(readTIFF(here("figures","study_design.tif")))
```

(ref:study-design-caption) Study design and endoscopically-acquired representative images of primary colorectal tumors. **A**: After AOM induction for six weeks, mice received either MTD NAC (20 mg/kg of 5-FU for five consecutive days every other week), MET NAC (8 mg/kg every other day three times a week), or saline (CG) treatment (200 $\mu$L). The next day after the first injection mice started to receive endoscopic examination which included DRS and biopsy acquisition. **B**: Representative images of endoscopic procedures and optically-derived perfusion values. _Top_: Biopsy acquisition using the biopsy forceps (indicated by arrow). _Bottom_: DRS probe (indicated by arrow) placement on a tumor previous to spectra acquisition. DRS probe diameter was $\approx$ 0.78 mm. _Right_: Representative optically-derived values of $\mbox{StO}_2$ obtained after spectra post-processing. Top line shows the reflectance from a tumor showing high $\mbox{StO}_2$, note the distinct Q-bands in the reflectance (between 500-575 nm). Bottom line shows reflectance from a hypoxic tumor, note the low $\mbox{StO}_2$ value and the flat profile of the reflectance in the 475-600 nm range. **C**: Representative endoscopic images of the changes in tumor size of the course of therapy. _Top_: Tumors from the CG group. _Middle_: Tumors from the MET group. Tumors in the CG and MET groups showed no reduction in size over the course of therapy, their size increasing as therapy progressed (top and middle). Arrows indicate tumor location, note the tumor vasculature which is endoscopically visible. _Bottom_: MTD-trated tumors. These tumors showed a cyclic pattern of tumor growth and shrinkage with every therapy cycle. Note the intense dark red color on the tumor on the left indicating hypoxia, and its change in color and reduction in size in the following colonoscopy (right).

## Endoscopic DRS and biopsy acquisition

The next day of the first 5-FU (or saline) injection, mice underwent a colonoscopy as previously described and DRS spectra were acquired as we have reported elsewhere [@mundo2020]. Briefly, DRS were acquired using a USB spectrometer (Flame-T, Ocean Insight), and a sub-millimeter probe (Myriad Fiber Imaging, Dudley, MA, US). The probe diameter was $\approx$ 0.78 mm, with $\approx$ 290$\mu$m SDS and was connected to the insufflation port of the endoscopic examination sheath while using a shutter to block the light from the colonoscopy system lamp to avoid contamination on the spectra. The light source for DRS acquisition was a tungsten halogen lamp (HL-2000, Ocean Insight) whose intensity was calibrated using a 5% reflectance standard (SRS-05-010, Labsphere). All spectra were collected using an integration time of 75 ms.

Spectra were post-processed to obtain perfusion values from tissue ($\mbox{StO}_2$, $\mbox{HbO}_2$, etc.) as we have described in detail elsewhere [@mundo2020]. Briefly, we used an inverse lookup table (LUT) model [@rajaram2008] to extract absorption and scattering properties from tumors from spectra which were used to obtain perfusion values. We used a custom algorithm to discard spectra with artifacts from operator movement, mouse breathing or excessive pressure at the tip of the probe [@mundo2020]. After DRS spectra were acquired, the endoscopic sheath was cleaned with 70% ethanol and RNAse Away (7002, ThermoFisher), and a biopsy from the tumor was obtained using a 3 Fr. biopsy forceps (61071 ZJ, Karl Storz). Biopsies were placed in RNALater (AM7021, ThermoFisher) using a 0.5 sterile microcentrifuge tube (022600001, Eppendorf) and stored at -80$^\circ$C. Biopsies for the MET and CG group were obtained at weeks 1, 4 and 6, whereas in the MTD group biopsies were acquired weekly. After biopsy acquisition mice were removed from anesthesia once no active bleeding from the biopsy site was determined. Endoscopies were repeated once every 7 days for a total of 6 colonoscopies for every mouse.

## Quantitative Real-Time PCR

Biopsies were homogenized over ice using a sonicator (Q55 Sonicator, QSonica), and total mRNA extraction was performed using the RNAeasy Micro Kit (74004, Qiagen) following manufacturer recommendations. Quality of the extracted mRNA was determined using a spectrophotometer (NanoDrop One, ThermoFisher), using samples whose 260/280 absorbance ratio ranged between 1.8-2.0 [@krebs2009;@fleige2006]. Reverse transcription to cDNA was performed using the SuperScript Synthesis VILO cDNA Kit (ThermoFisher, 11754050), and cDNA concentration was normalized at 2.5 ng/µL for all samples. 

From all the potential pro-angiogenic targets we chose _Vegf_ and _Hif-1a_ as they are known to be the main drivers of vascular development in tumors. Additionally, _Dek_ and _Stat3_ were used as they influence _Vegf_ expression in an _Hif-1a_ independent manner [@yu2004;@zhang2016]. To analyze the hypoxia-independent upregulation of _Hif-a_ we used _Raptor_ [@agani2013]. All primers were obtained from Integrated DNA Technologies (Coralville, Iowa, US) using sequences designed in-house that were BLASTed for specificity, and whose efficiency was determined using the standard curve method. Primer sequences, efficiencies, and corresponding annealing temperatures appear in Table S.1 in the Appendix. 

The Luna Universal qPCR Master Mix (NEB, M3003) was used for qPCR employing 2 µL of cDNA sample and 18 µL mix of master mix (water, primers and qPCR mix) per well in 96-well plates (HSP9601, Bio-Rad), which were sealed using transparent film (MSB1001, Bio-Rad). All qPCR experiments were performed in a CFX96 Real Time PCR system (Bio-Rad) and were run in triplicate. Changes in the relative mRNA expression of all genes were quantified using Pfaffl’s method [@pfaffl2001] with murine glyceraldehyde-3-phosphate dehydrogenase (Gaphd) as the housekeeping gene [@easwaran2003], and the expression of each gene in the CG group at week 1 as the normalizer.

## Immunostaining

After the 6th (last) endoscopy for DRS and biopsy acquisition, mice were euthanized and colons were excised and cleaned using phosphate-buffered saline solution.Tumors were identified by comparing their anatomical location with the available imaging data in each case. Samples were stored in 10% neutral-buffered formalin for 24 hours, rinsed in saline, and later professionally embedded in paraffin and prepared by IHC World (Ellicott City, MD, US). Samples were sectioned in the sagittal plane to a thickness of 5 $\mu$m prior to immunoperoxidase staining for Nestin-1 (Abcam, ab237036), a marker that is used to detect vessels in AOM-induced tumors [@dougherty2008;@dougherty2014]. 

## Image analysis

Tumor sections were imaged in an upright Nikon widefield microscope using a 10x objective (0.30 NA), and a gain of 1. Between 1-3 non-overlapping regions of interest (ROI) were obtained per sample, and in each ROI areas for segmentation were labeled as Nestin-positive (brown), background, or tissue (blue). The segmentation of each ROI was performed using the Trainable WEKA Segmentation from Fiji [@argandacarreras2017]. Between 1 to 4 regions of each label per ROI were manually selected and used to train the algorithm, followed by testing on the whole image. In each ROI, microvessel density (MVD) was quantified as the percentage of Nestin-positive area relative to total tissue area [@dougherty2008]. Additional details can be found in the Appendix.

## Statistical Analyses

Statistical analyses were performed in R (4.1.1) [@r] using RStudio (2022.02.0 Build 333) and the {tidyverse} [@wickham2019] and {mgcv} [@wood2010;@wood2017] packages. Specific information on the models used for each type of data is presented below.

### DRS and qPCR data

For the longitudinal data (DRS, qPCR) an assessment of the trends in the response over time showed that they did not follow a linear pattern (Figures \@ref(fig:GAM-DRS-plot), \@ref(fig:GAMs-qPCR-plot)). Therefore we fitted generalized additive models (GAMs) with an interaction between time and treatment in each case. A GAM is a model that allows to fit non-linear trends in longitudinal data by using basis functions, thus overcoming the limitation of linear models (such as repeated measures ANOVA or a linear mixed model) which give biased estimates when used in data with non-linear trends [@mundo2021]. Because GAMs allow the data to dictate the fit of the model, they are advantageous to perform comparisons between the different trends in the data. Pairwise comparisons between the different groups were obtained by calculating the difference in the fitted smooths in each case (the trend over time), and constructing a 95% simultaneous confidence interval (CI) around that difference [@rose2012; @mundo2021]. In this way, the time intervals where a significant difference exists between the fitted trends will correspond to those intervals of time where the simultaneous CI does not cover zero [@mundo2021;@simpson2018]. Because the simultaneous CIs contain the whole function at a nominal level (95%), they are robust against false positives [@wood2017]. Additional details which include the syntax for GAMs for DRS and qPCR data, and figures with pairwise comparisons for all groups can be found in the Appendix.

### Imaging Data

For the imaging data, a Kruskal Wallis test was performed for the MVD values between groups to determine any statistically significant differences. Significant _p-values_ were considered below 0.05.


