# Discussion

Although MTD NAC in CRC aims to maximize the number of cancerous cells to be killed, this ultimate goal is limited by the rest periods it requires which lead to tumor re-growth and resistance [@scharovsky2009;@boyer2006]. In recent years, there has been an ongoing interest in the use of doses of cytotoxic drugs below the MTD threshold, which has led to the development of MET as an alternative treatment strategy for cancer. However, so far MET has not been explored as an alternative to MTD NAC in CRC. A critical component that needs to be addressed before MET NAC can be studied at the clinical level in CRC pertains its effect on the angiogenic program of tumors. Because tumor response is a microenvironment-dependent process, there is a need to examine if MET is able to cause the same anti-angiogenic effect in primary tumors that has been previously reported in subcutaneous models of this disease [@bocci2008; @hoxuan2020]. 

In this regard, one way that tumor response to therapy (chemotherapy, radiotherapy or their combination) has been extensively studied in the past involves the use of DRS as a low-cost, non-destructive approach that quantifies changes in perfusion parameters ($\mbox{StO}_2$, $\mbox{HbO}_2$, etc.) which are known to change after therapy [@mundo2020; @ueda2012; @zhou2007; @tromberg2000; @hu2016; @vishwanath2009b]. However, perfusion values that are quantifiable via DRS only represent ‘high level’ view of a preceding sequence of molecular shifts in the angiogenic program of tumors.  Quantifying the changes in expression of genes involved in angiogenesis over the course of therapy may provide insight on the molecular mechanisms (‘low level’ changes) involved in the observed perfusion values obtained via DRS.

Specifically, because in the classical angiogenesis pathway the main driver of vascular development is _VEGF_ (itself being upregulated by _HIF-1A_ under hypoxic conditions [@simon2017]), we hypothesized that the use of endoscopic DRS and the longitudinal analysis of the levels of expression of _Vegf_ and _Hif-1a_ mRNA (and also the levels of mRNA from genes are known to upregulate _VEGF_ and _HIF-1A_ in an independent manner) would be able to provide a more comprehensive picture of the effect of MET and MTD NAC regimens in tumor angiogenesis in CRC. Our results suggest that while MET and MTD NAC elicit similar responses in perfusion, they cause distinct molecular responses in tumors under 5-FU chemotherapy. Considering the current interest in MET, our study points to the importance of the use of multimodal approaches that can provide insight on the different mechanisms that the angiogenic program of tumors undergo during therapy.

Our DRS results show that NAC (either MTD or MET) causes a similar effect in the trends of $\mbox{StO}_2$ and $\mbox{HbO}_2$ during the course of therapy, where an increase is observed during the first weeks of treatment followed by a gradual return to the baseline during the second half (Figure \@ref(fig:GAM-DRS-plot)A, B). The estimated differences between the trends of $\mbox{StO}_2$ indicate that in our model, MET causes an increase in oxygenation that can be detected via DRS and that becomes significant between weeks 2 and 5, whereas in the MTD the significant difference occurs between weeks 2 an 4 (Figure \@ref(fig:GAM-DRS-plot)E and F, respectively). Although only the MET group showed a statistically significant increase in $\mbox{HbO}_2$ when compared to the CG group between weeks 3 and 5 (Figure \@ref(fig:GAM-DRS-plot)G), the same trend was observed for the CG-MTD pariwise comparison (Figure S.2,B in the Appendix).

The significant increase in $\mbox{StO}_2$ we observed in the MET and MTD groups is consistent with the longitudinal elevation of this metric that has been reported in breast tumors, head and neck cancer xenografts and primary murine colorectal tumors after therapy [@vishwanath2009b;@hu2016; @tromberg2000]. In the past, the rationale for such increase has had multiple hypotheses: an increase in perfusion (when coupled with an increase in $\mbox{HbO}_2$) [@hu2016;@vishwanath2009;@dadgar2021], the generation of free radicals by cytotoxic drugs that damage the nucleic acids of cancerous cells [@tredan2007], changes in metabolism [@ueda2012], and decreased oxygen consumption in surrounding tissue [@dadgar2021]. However, so far there have been no studies that provide longitudinal molecular information to those observed changes in perfusion. Here, we addressed the need of providing molecular context to the observed changes in perfusion by quantifying mRNA expression in genes associated with angiogenesis.

In this regard, we started by quantifying the expression of _Vegf_ across all groups. Our analysis shows that both MET and MTD NAC are able to decrease the relative expression of _Vegf_ when compared to the levels of untreated tumors, but such reduction is only significant for the MTD group through the first 4 weeks of treatment when compared to the MET and CG groups (Figure \@ref(fig:GAMs-qPCR-pwcomp-plot)A, B) and can be measured 24-h after the first 5-FU injection. The average magnitude of the reduction is greater in the MTD group ($\approx$ 60%) when compared with the MET group ($\approx$ 29%). This would indicate that the increase in $\mbox{StO}_2$ that is found via DRS in the MTD group (when compared to the CG group) through weeks 2 and 4 is the physiologically measurable outcome of the reduction in _Vegf_ expression that starts at early at the beginning of the treatment phase, and that such increment in $\mbox{StO}_2$ is likely to be driven by an alteration of the tumor vasculature due to therapy (an anti-angiogenic effect). Interestingly, because in the MET group the change in $\mbox{StO}_2$ is not coupled with a significant change in _Vegf_ expression, it appears that this type of therapy is able to affect tumor perfusion without a concomitant anti-angiogenic effect. 

Additionally, because there was an endoscopically-visible reduction in tumor size between each therapy cycle in the MTD group (Figure \@ref(fig:study-design)C), the reduction in _Vegf_ expression, and similar trends in the increase of $\mbox{StO}_2$ and $\mbox{HbO}_2$ would indicate a reduction in oxygen demand in surrounding tissue due to the number of tumor cells killed after each round of therapy driven by an anti-angiogenic effect in MTD NAC, consistent with results we have previously reported [@mundo2020]. In other words, it appears that the magnitude of the decrease in _Vegf_ expression that MTD NAC is able to achieve (and that is significantly lower than that achieved in the MET group) leads to significant blood vessel reduction/remodeling in the tumor when compared to the MET and CG groups (Figure \@ref(fig:IHC-MVD-plot)C, D). Such result is consistent with the significant reduction of MVD in MTD-treated colorectal xenografts reported by Shi et. al.[@shi2014]. 

In the case of MET NAC, our observed non-statistically significant reduction in _Vegf_ expression using 5-FU in a MET regimen is in line with the results of a study by Fioravanti et. al. that addressed this same question [@fioravanti2009]. Taken together, our results suggest that the observed changes in angiogenesis in the MET group are caused by an increase in perfusion, consistent with previous studies that have provided the same rationale to a simultaneous increases in both $\mbox{StO}_2$ and $\mbox{HbO}_2$ in tumors after therapy [@hu2016;@vishwanath2009;@dadgar2021]. Furthermore, the changes in tHb through therapy show that in the MET group there is a significant increase between weeks 3 and 4 when compared to the CG group (Figure \@ref(fig:GAM-DRS-plot)H), but that the MET group showed a significant increase in tHb at week 5 when compared to the MTD group (Figure \@ref(fig:GAM-DRS-plot)I). Considering that by the end of therapy there is no significant difference in MVD between the MET and CG groups, but that the blood vessel area is significantly reduced in the MTD group (Figure \@ref(fig:IHC-MVD-plot)D) this would support our previous analysis of the effects of each type of therapy in the angiogenic program of tumors. Specifically, there seems to be a distinct anti-angiogenic effect of MTD NAC in our model which leads to a remodeling of the tumor vasculature which results in reduced tHb. In contrast, the increase in tHb in the MET group seems not to come from an anti-angiogenic effect of therapy in the tumor vasculature and at the end of the treatment, there is no discernable difference between vessels in the CG and MET groups. 

Additionally, the reduction in _Hif-1a_ mRNA expression in the MTD group was significant when compared to the MET and CG groups (Figures \@ref(fig:GAMs-qPCR-plot)B and \@ref(fig:GAMs-qPCR-pwcomp-plot)C, D). Interestingly, in both NAC groups the mean reduction in _Hif-1a_ expression at week 1 ($\approx$ 25% and 60% for MET and MTD, respetively) closely matched the observed mean reduction in _Vegf_ expression at the same timepoint. However, only in the MTD group the expression of both _Hif-1a_ and _Vegf_ followed the same overall trend (Figure \@ref(fig:GAMs-qPCR-plot)A, B). Despite the fact that the connection between _Hif-1a_ and _Vegf_ to drive angiogenesis is well established [@hicklin2005], there are no studies that analyze their expression in a longitudinal manner in tumors. In this case, at the very least, the similar levels of expression, longitudinal trends obtained for both genes, and the visually observable reduction in tumor size that MTD NAC causes suggest that in primary colorectal malignancies MTD NAC is able to effectively disrupt the VEGF-HIF-1a axis, thereby leading to a lasting anti-angiogenic effect that is not observable in MET NAC.

However, it is well established that HIF-1A is post-transcriptionally regulated under hypoxia [@hicklin2005], and therefore its effect is better quantified using downstream-regulated genes. To address this, we analyzed the levels of mRNA expression of two genes that encode enzymes involved in glycolysis and that are regulated by _Hif-1a_:  _Aldoa_ (_aldolase A_, one of the isoforms of the aldolase family) [@chang2018] and _Pgk1_ (_phosphoglycerate kinase 1_), which is one of the two ATP-generating enzymes in glycolysis [@qian2017]. Our results show that in the CG and MEG groups, the mRNA expression of _Hif-1a_, _Aldoa_, and _Pgk1_ has a similar trend  (Figure \@ref(fig:GAMs-qPCR-plot)D, F). This result suggests that the majority of _Hif-1a_ mRNA is not being post-transcriptionally degraded, thus being able to regulate _Aldoa_ and _Pgk1_ activity. Additionally, the pairwise comparisons for the smooth trends for both _Aldoa_ and _Pgk1_ show significant differences between the CG and MET groups between weeks 3 and 4 (Figure \@ref(fig:GAMs-qPCR-pwcomp-plot)E, I), which is the time when the expression in the MET group is higher. 

Interestingly, _Pgk1_ and _Aldoa_ do not show similar trends in expression with _Hif-1a_ as seen in the MET and CG groups; in this case, there are significant differences between the MET and MTD groups during weeks 3 and 4 (_Aldoa_), and from week 2 until week 6 (_Pgk1_) (Figure \@ref(fig:GAMs-qPCR-pwcomp-plot)F, K). This indicates the possibility of significant changes in metabolism caused by the dosing and frequency of therapy at the indicated time periods. It has been recently shown that in CRC cell lines, increased ALDOA expression enhances glycolysis by increasing glucose consumption and lactate production [@lin2022], whereas in clinical samples PGK1 enhances proliferation [@ge2019]. Taken together, our results suggest that MET NAC enhances glycolysis and proliferation, whereas MTD NAC is able to suppress a glycolysis-driven metabolism in primary colorectal tumors. Additionally, the fact that increased _Hif-1a_, _Pgk1_ and _Aldoa_ expression are significantly different during extended time intervals when compared to the expression and smooth trends from the MTD group poses a question of the potential adverse effects of MET NAC in CRC. Because the efficacy of MET is dependent on the combined effect of drug dosing and frequency, our results indicate that a necessary step before the translation of MET NAC to the clinic involves drug dose and frequency optimization as it is possible that sub-optimal combinations are able to trigger resistance mechanisms (such as glycolysis upregulation) instead of limiting tumor growth.

Because angiogenesis is a complex process that does not rely exclusively on hypoxia to occur, we also analyzed three genes that regulate VEGF and HIF-1a by independent mechanisms. In the case of VEGF, we analyzed _Stat3_ and _Dek_, which are known to regulate VEGF in a HIF-1a independent manner [@yu2004;@zhang2016]. For _Hif-1a_  we analyzed _Raptor_, as it encodes the RAPTOR protein which in turn regulates HIF-1a in an oxygen-independent manner [@yu2004;@agani2013;@semenza2010]. 

For _Raptor_, the trend in expression in the MET group remains relatively flat and similar in magnitude to that of the CG group, but the MTD group shows decreased expression at week 1 ($\approx$ 50%) (Figure \@ref(fig:GAMs-qPCR-plot)G). Moreover, significant differences exist in _Raptor_ expression between the CG and MTD groups (between weeks 5 and 6), and the MET-MTD groups (beginning of week 1 until the end of the study) \@ref(fig:GAMs-qPCR-pwcomp-plot)G, H). No significant differences were found between the pairwise smooth comparisons for _Stat3_ and _Dek_ across all treatment groups, indicating that both genes do not play a major role in regulating  _Vegf_ expression in primary colorectal tumors (Figure S.2 in the Appendix). 

In the past, DRS has been used to quantify tumor response to therapy [@vishwanath2009;@mundo2020;@dadgar2021], including the assessment of tumor response to MET in breast cancer [@tank2020]. Because DRS is minimally invasive, it provides information about early changes in perfusion after therapy, which can be used to evaluate the efficacy of different treatment strategies. However, because DRS is unable to provide metabolic or molecular information to the observed changes in perfusion, it is difficult to validate the hypotheses that can be inferred from such changes [@tredan2007; @ueda2012; @hu2016]. Traditionally, immunohistochemistry has been used to provide molecular context to DRS [@dadgar2021], but this approach is limited as it is destructive and leads to a progressive reduction animal numbers in preclinical research which can in turn affect statistical power. In contrast, the analysis of changes in RNA expression in tumor biopsies can be used to obtain a sequential view of changes in tumor biology without the trade-off in the number of live specimens that immunohistochemistry presents. Our study shows that the analysis of mRNA expression can provide better context and support or refute hypotheses that can attempt to explain the molecular background of observed changes in perfusion via DRS. Specifically, it is interesting to note that in our model, similar trends in $\mbox{StO}_2$ and $\mbox{HbO}_2$ across different treatment strategies can have very different interpretations when analyzed in conjunction with mRNA expression.

On the other hand, the endosocopic application of DRS and the acquisition of colorectal tumor biopsies (where the placement of the instruments is done in an indirect manner) presents multiple challenges which can lead to artifacts in the collected signal due to pressure or probe misplacement [@mundo2020], or to obtaining biopsies or from non-matching sites. Despite this, we believe that due to their relative low cost and minimally invasive nautre, optical methods (such as DRS) can provide useful information of tumor biology when used longitudinally _in vivo_ as there is potential in the use of the information generated by these technologies to determine their correlation with molecular markers of treatment response in CRC. In this way, DRS can be used to better to better understand the effects of therapy with regard to tumor resistance. Additionally, there is a need to obtain longitudinal information from tumors at the molecular level (using qPCR, RNA-seq, etc.) as such methods can provide powerful insight on the periods of increased cellular activity or changes in metabolism that can be exploited by novel therapeutic drugs and treatment strategies.

In summary, in this study we used a combination of diffuse reflectance spectroscopy and mRNA expression (via qPCR) to longitudinally assess changes in the angiogenic program of primary colorectal tumors under MTD and MET NAC regimens. In our model, MET and MTD NAC cause an increase in oxygen saturation in tumors that is quantifiable via DRS and becomes significant between the third and fourth week of treatment. When paired with the trends in mRNA expression, additional context can be provided to the observed changes in oxygenation. In the MTD group the increase in saturation is driven by reduced oxygen demand and is coupled with a significant reduction in _Vegf_ expression when compared to tumors treated with MET NAC; such reduction leads to the remodeling of blood vessels, therefore causing decrease in MVD, which is quantifiable at the end of therapy. In MET-treated tumors the increase in oxygen saturation is caused by an increase in perfusion, and because _Aldoa_ and _Pgk1_ have increased expression, glycolysis appears to be upregulated in the MET group. Our study also demonstrates that when used in tandem, optical and molecular techniques can provide a comprehensive picture in the effects of novel treatment strategies. Our long term goal is to incorporate RNA-seq and optical techniques (DRS, multiphoton microscopy, fluorescence lifetime imaging) to holistically examine tumor biology and identify opportunities and challenges for novel therapeutic approaches in colorectal cancer. Future work will also incorporate the use of male mice to address potential sex-specific effects of chemotherapy.

# Acknowledgments

This work was supported by the National Science Foundation CAREER Award (CBET 1751554, TJM), the Arkansas Biosciences Institute (TJM, AM), and the Fulbright Commission (Faculty Development Program, AM). The authors thank Regina Cabrera and Eleanor Schrems for their help with animal care, endoscopic procedures, and data acquisition.

# Conflicts of interest

The authors report no conflict of interest.

